### ISSUE TITLE
Swift Package

### ISSUE THREAD

**Issue by ronyfadel** [zsergey/Apple-Inspired-Puller#1]
I'd like to use this in my apps but a Swift Package is missing

**Comment by zsergey** [comment]
I'm going to add support of SwiftUI and then I will add Swift Package for you.

Thanks, Rony!

**Comment by zsergey** [comment]
It was not easy to support `UIHostingController` and I found a global issue. `List` highlights the issue. 

Updated: Added `DemoScrollView` and `DemoList` in SwiftUI.

**Comment by zsergey** [comment]
Now It fully supports SwiftUI cause you can use `.puller` modifier from SwiftUI's code. But It has an issue of `UIHostingController` similar like https://forums.swift.org/t/uihostingcontroller-inside-uiview-bug-when-moving/55061

**Comment by zsergey** [comment]
The puller is ready to use, @ronyfadel 🎉
