### ISSUE TITLE
Puller in ModalViewController

### ISSUE THREAD

**Issue by Alelenka** [zsergey/Apple-Inspired-Puller#3]
Love the puller! Want to use it!

But when puller open from modalViewController - shrink animation for controller in background in LargeState is strange(

![Simulator Screen Recording - iPhone 14 Pro - 2023-04-13 at 12 00 01](https://user-images.githubusercontent.com/4083274/231709367-633bfe84-b770-47de-bbc8-0d51881d9e9c.gif)

**Comment by zsergey** [comment]
Thank you! I will check it.

**Comment by zsergey** [comment]
I checked how it works in Apple's sheet and did the same behaviour in the puller. Is it your case?

<img src="https://user-images.githubusercontent.com/1423911/232028594-50f41f36-aa6d-4e06-843f-3520a90bccd1.gif" height="600" width="278">
